// @generated by protoc-gen-es v1.10.0
// @generated from file placeholder/v1/placeholder.proto (package placeholder.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * Walking-skeleton placeholder. Slice 2 replaces this module with the real
 * common/v1/common.proto and service contracts.
 *
 * @generated from message placeholder.v1.Placeholder
 */
export const Placeholder = /*@__PURE__*/ proto3.makeMessageType(
  "placeholder.v1.Placeholder",
  () => [
    { no: 1, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

