// @generated by protoc-gen-es v1.10.0
// @generated from file placeholder/v1/placeholder.proto (package placeholder.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Walking-skeleton placeholder. Slice 2 replaces this module with the real
 * common/v1/common.proto and service contracts.
 *
 * @generated from message placeholder.v1.Placeholder
 */
export declare class Placeholder extends Message<Placeholder> {
  /**
   * @generated from field: string value = 1;
   */
  value: string;

  constructor(data?: PartialMessage<Placeholder>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "placeholder.v1.Placeholder";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Placeholder;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Placeholder;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Placeholder;

  static equals(a: Placeholder | PlainMessage<Placeholder> | undefined, b: Placeholder | PlainMessage<Placeholder> | undefined): boolean;
}

