// Shipment Service — the system of record for the shipment lifecycle.

// @generated by protoc-gen-connect-es v1.6.1
// @generated from file cargo/shipment/v1/shipment.proto (package cargo.shipment.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelShipmentRequest, CancelShipmentResponse, CreateShipmentRequest, CreateShipmentResponse, GetShipmentRequest, GetShipmentResponse, ListShipmentsRequest, ListShipmentsResponse, UpdateShipmentStatusRequest, UpdateShipmentStatusResponse } from "./shipment_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * System of record for shipments.
 *
 * @generated from service cargo.shipment.v1.ShipmentService
 */
export const ShipmentService = {
  typeName: "cargo.shipment.v1.ShipmentService",
  methods: {
    /**
     * @generated from rpc cargo.shipment.v1.ShipmentService.CreateShipment
     */
    createShipment: {
      name: "CreateShipment",
      I: CreateShipmentRequest,
      O: CreateShipmentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cargo.shipment.v1.ShipmentService.GetShipment
     */
    getShipment: {
      name: "GetShipment",
      I: GetShipmentRequest,
      O: GetShipmentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cargo.shipment.v1.ShipmentService.ListShipments
     */
    listShipments: {
      name: "ListShipments",
      I: ListShipmentsRequest,
      O: ListShipmentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cargo.shipment.v1.ShipmentService.UpdateShipmentStatus
     */
    updateShipmentStatus: {
      name: "UpdateShipmentStatus",
      I: UpdateShipmentStatusRequest,
      O: UpdateShipmentStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cargo.shipment.v1.ShipmentService.CancelShipment
     */
    cancelShipment: {
      name: "CancelShipment",
      I: CancelShipmentRequest,
      O: CancelShipmentResponse,
      kind: MethodKind.Unary,
    },
  }
};

