// Shipment Service — the system of record for the shipment lifecycle.

// @generated by protoc-gen-connect-es v1.6.1
// @generated from file cargo/shipment/v1/shipment.proto (package cargo.shipment.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelShipmentRequest, CancelShipmentResponse, CreateShipmentRequest, CreateShipmentResponse, GetShipmentRequest, GetShipmentResponse, ListShipmentsRequest, ListShipmentsResponse, UpdateShipmentStatusRequest, UpdateShipmentStatusResponse } from "./shipment_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * System of record for shipments.
 *
 * @generated from service cargo.shipment.v1.ShipmentService
 */
export declare const ShipmentService: {
  readonly typeName: "cargo.shipment.v1.ShipmentService",
  readonly methods: {
    /**
     * @generated from rpc cargo.shipment.v1.ShipmentService.CreateShipment
     */
    readonly createShipment: {
      readonly name: "CreateShipment",
      readonly I: typeof CreateShipmentRequest,
      readonly O: typeof CreateShipmentResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cargo.shipment.v1.ShipmentService.GetShipment
     */
    readonly getShipment: {
      readonly name: "GetShipment",
      readonly I: typeof GetShipmentRequest,
      readonly O: typeof GetShipmentResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cargo.shipment.v1.ShipmentService.ListShipments
     */
    readonly listShipments: {
      readonly name: "ListShipments",
      readonly I: typeof ListShipmentsRequest,
      readonly O: typeof ListShipmentsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cargo.shipment.v1.ShipmentService.UpdateShipmentStatus
     */
    readonly updateShipmentStatus: {
      readonly name: "UpdateShipmentStatus",
      readonly I: typeof UpdateShipmentStatusRequest,
      readonly O: typeof UpdateShipmentStatusResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cargo.shipment.v1.ShipmentService.CancelShipment
     */
    readonly cancelShipment: {
      readonly name: "CancelShipment",
      readonly I: typeof CancelShipmentRequest,
      readonly O: typeof CancelShipmentResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

