// Shipment Service — the system of record for the shipment lifecycle.

// @generated by protoc-gen-es v1.10.0
// @generated from file cargo/shipment/v1/shipment.proto (package cargo.shipment.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Address, Page, PageResult } from "../../common/v1/common_pb.js";

/**
 * Legal states a shipment can be in. Transitions are enforced by the
 * Shipment Service; illegal jumps return FAILED_PRECONDITION.
 *
 * @generated from enum cargo.shipment.v1.ShipmentStatus
 */
export declare enum ShipmentStatus {
  /**
   * @generated from enum value: SHIPMENT_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SHIPMENT_STATUS_CREATED = 1;
   */
  CREATED = 1,

  /**
   * @generated from enum value: SHIPMENT_STATUS_IN_TRANSIT = 2;
   */
  IN_TRANSIT = 2,

  /**
   * @generated from enum value: SHIPMENT_STATUS_DELIVERED = 3;
   */
  DELIVERED = 3,

  /**
   * @generated from enum value: SHIPMENT_STATUS_CANCELLED = 4;
   */
  CANCELLED = 4,
}

/**
 * The shipment aggregate as returned by the service.
 *
 * @generated from message cargo.shipment.v1.Shipment
 */
export declare class Shipment extends Message<Shipment> {
  /**
   * Server-assigned UUID.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Human-friendly code, e.g. CT-2026-000123. Unique across all shipments.
   *
   * @generated from field: string tracking_code = 2;
   */
  trackingCode: string;

  /**
   * @generated from field: cargo.common.v1.Address origin = 3;
   */
  origin?: Address;

  /**
   * @generated from field: cargo.common.v1.Address destination = 4;
   */
  destination?: Address;

  /**
   * Carrier handling the delivery (e.g. "DHL", "UPS").
   *
   * @generated from field: string carrier = 5;
   */
  carrier: string;

  /**
   * @generated from field: cargo.shipment.v1.ShipmentStatus status = 6;
   */
  status: ShipmentStatus;

  /**
   * @generated from field: double weight_kg = 7;
   */
  weightKg: number;

  /**
   * Estimated time of arrival. Nullable until assigned.
   *
   * @generated from field: google.protobuf.Timestamp eta = 8;
   */
  eta?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 9;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 10;
   */
  updatedAt?: Timestamp;

  constructor(data?: PartialMessage<Shipment>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.shipment.v1.Shipment";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Shipment;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Shipment;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Shipment;

  static equals(a: Shipment | PlainMessage<Shipment> | undefined, b: Shipment | PlainMessage<Shipment> | undefined): boolean;
}

/**
 * CreateShipment — register a new shipment, status starts at CREATED.
 *
 * @generated from message cargo.shipment.v1.CreateShipmentRequest
 */
export declare class CreateShipmentRequest extends Message<CreateShipmentRequest> {
  /**
   * @generated from field: cargo.common.v1.Address origin = 1;
   */
  origin?: Address;

  /**
   * @generated from field: cargo.common.v1.Address destination = 2;
   */
  destination?: Address;

  /**
   * @generated from field: string carrier = 3;
   */
  carrier: string;

  /**
   * @generated from field: double weight_kg = 4;
   */
  weightKg: number;

  constructor(data?: PartialMessage<CreateShipmentRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.shipment.v1.CreateShipmentRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateShipmentRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateShipmentRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateShipmentRequest;

  static equals(a: CreateShipmentRequest | PlainMessage<CreateShipmentRequest> | undefined, b: CreateShipmentRequest | PlainMessage<CreateShipmentRequest> | undefined): boolean;
}

/**
 * @generated from message cargo.shipment.v1.CreateShipmentResponse
 */
export declare class CreateShipmentResponse extends Message<CreateShipmentResponse> {
  /**
   * @generated from field: cargo.shipment.v1.Shipment shipment = 1;
   */
  shipment?: Shipment;

  constructor(data?: PartialMessage<CreateShipmentResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.shipment.v1.CreateShipmentResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateShipmentResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateShipmentResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateShipmentResponse;

  static equals(a: CreateShipmentResponse | PlainMessage<CreateShipmentResponse> | undefined, b: CreateShipmentResponse | PlainMessage<CreateShipmentResponse> | undefined): boolean;
}

/**
 * GetShipment — look up by server id or by human tracking code.
 *
 * @generated from message cargo.shipment.v1.GetShipmentRequest
 */
export declare class GetShipmentRequest extends Message<GetShipmentRequest> {
  /**
   * @generated from oneof cargo.shipment.v1.GetShipmentRequest.key
   */
  key: {
    /**
     * @generated from field: string id = 1;
     */
    value: string;
    case: "id";
  } | {
    /**
     * @generated from field: string tracking_code = 2;
     */
    value: string;
    case: "trackingCode";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<GetShipmentRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.shipment.v1.GetShipmentRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetShipmentRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetShipmentRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetShipmentRequest;

  static equals(a: GetShipmentRequest | PlainMessage<GetShipmentRequest> | undefined, b: GetShipmentRequest | PlainMessage<GetShipmentRequest> | undefined): boolean;
}

/**
 * @generated from message cargo.shipment.v1.GetShipmentResponse
 */
export declare class GetShipmentResponse extends Message<GetShipmentResponse> {
  /**
   * @generated from field: cargo.shipment.v1.Shipment shipment = 1;
   */
  shipment?: Shipment;

  constructor(data?: PartialMessage<GetShipmentResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.shipment.v1.GetShipmentResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetShipmentResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetShipmentResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetShipmentResponse;

  static equals(a: GetShipmentResponse | PlainMessage<GetShipmentResponse> | undefined, b: GetShipmentResponse | PlainMessage<GetShipmentResponse> | undefined): boolean;
}

/**
 * ListShipments — cursor-paginated, filterable by status and carrier.
 *
 * @generated from message cargo.shipment.v1.ListShipmentsRequest
 */
export declare class ListShipmentsRequest extends Message<ListShipmentsRequest> {
  /**
   * Optional. Restrict results to this status.
   *
   * @generated from field: cargo.shipment.v1.ShipmentStatus status_filter = 1;
   */
  statusFilter: ShipmentStatus;

  /**
   * Optional. Restrict results to this carrier.
   *
   * @generated from field: string carrier_filter = 2;
   */
  carrierFilter: string;

  /**
   * @generated from field: cargo.common.v1.Page page = 3;
   */
  page?: Page;

  constructor(data?: PartialMessage<ListShipmentsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.shipment.v1.ListShipmentsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListShipmentsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListShipmentsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListShipmentsRequest;

  static equals(a: ListShipmentsRequest | PlainMessage<ListShipmentsRequest> | undefined, b: ListShipmentsRequest | PlainMessage<ListShipmentsRequest> | undefined): boolean;
}

/**
 * @generated from message cargo.shipment.v1.ListShipmentsResponse
 */
export declare class ListShipmentsResponse extends Message<ListShipmentsResponse> {
  /**
   * @generated from field: repeated cargo.shipment.v1.Shipment shipments = 1;
   */
  shipments: Shipment[];

  /**
   * @generated from field: cargo.common.v1.PageResult page = 2;
   */
  page?: PageResult;

  constructor(data?: PartialMessage<ListShipmentsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.shipment.v1.ListShipmentsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListShipmentsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListShipmentsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListShipmentsResponse;

  static equals(a: ListShipmentsResponse | PlainMessage<ListShipmentsResponse> | undefined, b: ListShipmentsResponse | PlainMessage<ListShipmentsResponse> | undefined): boolean;
}

/**
 * UpdateShipmentStatus — transition between legal states. Illegal jumps
 * return FAILED_PRECONDITION.
 *
 * @generated from message cargo.shipment.v1.UpdateShipmentStatusRequest
 */
export declare class UpdateShipmentStatusRequest extends Message<UpdateShipmentStatusRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: cargo.shipment.v1.ShipmentStatus new_status = 2;
   */
  newStatus: ShipmentStatus;

  constructor(data?: PartialMessage<UpdateShipmentStatusRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.shipment.v1.UpdateShipmentStatusRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateShipmentStatusRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateShipmentStatusRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateShipmentStatusRequest;

  static equals(a: UpdateShipmentStatusRequest | PlainMessage<UpdateShipmentStatusRequest> | undefined, b: UpdateShipmentStatusRequest | PlainMessage<UpdateShipmentStatusRequest> | undefined): boolean;
}

/**
 * @generated from message cargo.shipment.v1.UpdateShipmentStatusResponse
 */
export declare class UpdateShipmentStatusResponse extends Message<UpdateShipmentStatusResponse> {
  /**
   * @generated from field: cargo.shipment.v1.Shipment shipment = 1;
   */
  shipment?: Shipment;

  constructor(data?: PartialMessage<UpdateShipmentStatusResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.shipment.v1.UpdateShipmentStatusResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateShipmentStatusResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateShipmentStatusResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateShipmentStatusResponse;

  static equals(a: UpdateShipmentStatusResponse | PlainMessage<UpdateShipmentStatusResponse> | undefined, b: UpdateShipmentStatusResponse | PlainMessage<UpdateShipmentStatusResponse> | undefined): boolean;
}

/**
 * CancelShipment — only allowed from CREATED or IN_TRANSIT.
 *
 * @generated from message cargo.shipment.v1.CancelShipmentRequest
 */
export declare class CancelShipmentRequest extends Message<CancelShipmentRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  constructor(data?: PartialMessage<CancelShipmentRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.shipment.v1.CancelShipmentRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelShipmentRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelShipmentRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelShipmentRequest;

  static equals(a: CancelShipmentRequest | PlainMessage<CancelShipmentRequest> | undefined, b: CancelShipmentRequest | PlainMessage<CancelShipmentRequest> | undefined): boolean;
}

/**
 * @generated from message cargo.shipment.v1.CancelShipmentResponse
 */
export declare class CancelShipmentResponse extends Message<CancelShipmentResponse> {
  /**
   * @generated from field: cargo.shipment.v1.Shipment shipment = 1;
   */
  shipment?: Shipment;

  constructor(data?: PartialMessage<CancelShipmentResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.shipment.v1.CancelShipmentResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelShipmentResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelShipmentResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelShipmentResponse;

  static equals(a: CancelShipmentResponse | PlainMessage<CancelShipmentResponse> | undefined, b: CancelShipmentResponse | PlainMessage<CancelShipmentResponse> | undefined): boolean;
}

