// Shipment Service — the system of record for the shipment lifecycle.

// @generated by protoc-gen-es v1.10.0
// @generated from file cargo/shipment/v1/shipment.proto (package cargo.shipment.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";
import { Address, Page, PageResult } from "../../common/v1/common_pb.js";

/**
 * Legal states a shipment can be in. Transitions are enforced by the
 * Shipment Service; illegal jumps return FAILED_PRECONDITION.
 *
 * @generated from enum cargo.shipment.v1.ShipmentStatus
 */
export const ShipmentStatus = /*@__PURE__*/ proto3.makeEnum(
  "cargo.shipment.v1.ShipmentStatus",
  [
    {no: 0, name: "SHIPMENT_STATUS_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "SHIPMENT_STATUS_CREATED", localName: "CREATED"},
    {no: 2, name: "SHIPMENT_STATUS_IN_TRANSIT", localName: "IN_TRANSIT"},
    {no: 3, name: "SHIPMENT_STATUS_DELIVERED", localName: "DELIVERED"},
    {no: 4, name: "SHIPMENT_STATUS_CANCELLED", localName: "CANCELLED"},
  ],
);

/**
 * The shipment aggregate as returned by the service.
 *
 * @generated from message cargo.shipment.v1.Shipment
 */
export const Shipment = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.shipment.v1.Shipment",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "tracking_code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "origin", kind: "message", T: Address },
    { no: 4, name: "destination", kind: "message", T: Address },
    { no: 5, name: "carrier", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "status", kind: "enum", T: proto3.getEnumType(ShipmentStatus) },
    { no: 7, name: "weight_kg", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 8, name: "eta", kind: "message", T: Timestamp },
    { no: 9, name: "created_at", kind: "message", T: Timestamp },
    { no: 10, name: "updated_at", kind: "message", T: Timestamp },
  ],
);

/**
 * CreateShipment — register a new shipment, status starts at CREATED.
 *
 * @generated from message cargo.shipment.v1.CreateShipmentRequest
 */
export const CreateShipmentRequest = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.shipment.v1.CreateShipmentRequest",
  () => [
    { no: 1, name: "origin", kind: "message", T: Address },
    { no: 2, name: "destination", kind: "message", T: Address },
    { no: 3, name: "carrier", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "weight_kg", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * @generated from message cargo.shipment.v1.CreateShipmentResponse
 */
export const CreateShipmentResponse = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.shipment.v1.CreateShipmentResponse",
  () => [
    { no: 1, name: "shipment", kind: "message", T: Shipment },
  ],
);

/**
 * GetShipment — look up by server id or by human tracking code.
 *
 * @generated from message cargo.shipment.v1.GetShipmentRequest
 */
export const GetShipmentRequest = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.shipment.v1.GetShipmentRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "key" },
    { no: 2, name: "tracking_code", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "key" },
  ],
);

/**
 * @generated from message cargo.shipment.v1.GetShipmentResponse
 */
export const GetShipmentResponse = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.shipment.v1.GetShipmentResponse",
  () => [
    { no: 1, name: "shipment", kind: "message", T: Shipment },
  ],
);

/**
 * ListShipments — cursor-paginated, filterable by status and carrier.
 *
 * @generated from message cargo.shipment.v1.ListShipmentsRequest
 */
export const ListShipmentsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.shipment.v1.ListShipmentsRequest",
  () => [
    { no: 1, name: "status_filter", kind: "enum", T: proto3.getEnumType(ShipmentStatus) },
    { no: 2, name: "carrier_filter", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "page", kind: "message", T: Page },
  ],
);

/**
 * @generated from message cargo.shipment.v1.ListShipmentsResponse
 */
export const ListShipmentsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.shipment.v1.ListShipmentsResponse",
  () => [
    { no: 1, name: "shipments", kind: "message", T: Shipment, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageResult },
  ],
);

/**
 * UpdateShipmentStatus — transition between legal states. Illegal jumps
 * return FAILED_PRECONDITION.
 *
 * @generated from message cargo.shipment.v1.UpdateShipmentStatusRequest
 */
export const UpdateShipmentStatusRequest = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.shipment.v1.UpdateShipmentStatusRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "new_status", kind: "enum", T: proto3.getEnumType(ShipmentStatus) },
  ],
);

/**
 * @generated from message cargo.shipment.v1.UpdateShipmentStatusResponse
 */
export const UpdateShipmentStatusResponse = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.shipment.v1.UpdateShipmentStatusResponse",
  () => [
    { no: 1, name: "shipment", kind: "message", T: Shipment },
  ],
);

/**
 * CancelShipment — only allowed from CREATED or IN_TRANSIT.
 *
 * @generated from message cargo.shipment.v1.CancelShipmentRequest
 */
export const CancelShipmentRequest = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.shipment.v1.CancelShipmentRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message cargo.shipment.v1.CancelShipmentResponse
 */
export const CancelShipmentResponse = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.shipment.v1.CancelShipmentResponse",
  () => [
    { no: 1, name: "shipment", kind: "message", T: Shipment },
  ],
);

