// Shared types used by more than one cargo tracking service.

// @generated by protoc-gen-es v1.10.0
// @generated from file cargo/common/v1/common.proto (package cargo.common.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * A postal address. Used on the origin and destination of every shipment.
 *
 * @generated from message cargo.common.v1.Address
 */
export declare class Address extends Message<Address> {
  /**
   * @generated from field: string line1 = 1;
   */
  line1: string;

  /**
   * @generated from field: string city = 2;
   */
  city: string;

  /**
   * @generated from field: string country = 3;
   */
  country: string;

  /**
   * @generated from field: string postal_code = 4;
   */
  postalCode: string;

  constructor(data?: PartialMessage<Address>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.common.v1.Address";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Address;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Address;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Address;

  static equals(a: Address | PlainMessage<Address> | undefined, b: Address | PlainMessage<Address> | undefined): boolean;
}

/**
 * Opaque pagination cursor consumed by list RPCs.
 *
 * @generated from message cargo.common.v1.Page
 */
export declare class Page extends Message<Page> {
  /**
   * Maximum number of items to return. Server caps at 100.
   *
   * @generated from field: int32 size = 1;
   */
  size: number;

  /**
   * Opaque continuation token returned by a previous call.
   *
   * @generated from field: string token = 2;
   */
  token: string;

  constructor(data?: PartialMessage<Page>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.common.v1.Page";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Page;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Page;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Page;

  static equals(a: Page | PlainMessage<Page> | undefined, b: Page | PlainMessage<Page> | undefined): boolean;
}

/**
 * Continuation token returned by a list RPC.
 *
 * @generated from message cargo.common.v1.PageResult
 */
export declare class PageResult extends Message<PageResult> {
  /**
   * Token to pass back in the next request. Empty when there are no more pages.
   *
   * @generated from field: string next_token = 1;
   */
  nextToken: string;

  constructor(data?: PartialMessage<PageResult>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.common.v1.PageResult";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageResult;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageResult;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageResult;

  static equals(a: PageResult | PlainMessage<PageResult> | undefined, b: PageResult | PlainMessage<PageResult> | undefined): boolean;
}

