// Shared types used by more than one cargo tracking service.

// @generated by protoc-gen-es v1.10.0
// @generated from file cargo/common/v1/common.proto (package cargo.common.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * A postal address. Used on the origin and destination of every shipment.
 *
 * @generated from message cargo.common.v1.Address
 */
export const Address = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.common.v1.Address",
  () => [
    { no: 1, name: "line1", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "city", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "country", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "postal_code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * Opaque pagination cursor consumed by list RPCs.
 *
 * @generated from message cargo.common.v1.Page
 */
export const Page = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.common.v1.Page",
  () => [
    { no: 1, name: "size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * Continuation token returned by a list RPC.
 *
 * @generated from message cargo.common.v1.PageResult
 */
export const PageResult = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.common.v1.PageResult",
  () => [
    { no: 1, name: "next_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

