// Tracking Service — live geo-location ingest, read model, and
// server-streaming subscriptions for a single shipment.

// @generated by protoc-gen-es v1.10.0
// @generated from file cargo/tracking/v1/tracking.proto (package cargo.tracking.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { ShipmentStatus } from "../../shipment/v1/shipment_pb.js";

/**
 * A single geo-location ping reported for a shipment.
 *
 * @generated from message cargo.tracking.v1.TrackingEvent
 */
export declare class TrackingEvent extends Message<TrackingEvent> {
  /**
   * Server-assigned UUID for the event.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Shipment this event belongs to (Shipment.id, not tracking_code).
   *
   * @generated from field: string shipment_id = 2;
   */
  shipmentId: string;

  /**
   * @generated from field: double lat = 3;
   */
  lat: number;

  /**
   * @generated from field: double lng = 4;
   */
  lng: number;

  /**
   * Wall-clock time the ping was recorded at the source device.
   *
   * @generated from field: google.protobuf.Timestamp recorded_at = 5;
   */
  recordedAt?: Timestamp;

  /**
   * Free-form identifier for the producer (driver app, IoT device, test
   * client). Used for observability only — not part of the aggregate key.
   *
   * @generated from field: string source = 6;
   */
  source: string;

  constructor(data?: PartialMessage<TrackingEvent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.tracking.v1.TrackingEvent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TrackingEvent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TrackingEvent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TrackingEvent;

  static equals(a: TrackingEvent | PlainMessage<TrackingEvent> | undefined, b: TrackingEvent | PlainMessage<TrackingEvent> | undefined): boolean;
}

/**
 * ReportLocation — push a single tracking ping. Idempotent on event.id
 * so retries (e.g. from the simulated test client) are safe.
 *
 * @generated from message cargo.tracking.v1.ReportLocationRequest
 */
export declare class ReportLocationRequest extends Message<ReportLocationRequest> {
  /**
   * @generated from field: cargo.tracking.v1.TrackingEvent event = 1;
   */
  event?: TrackingEvent;

  constructor(data?: PartialMessage<ReportLocationRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.tracking.v1.ReportLocationRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReportLocationRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReportLocationRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReportLocationRequest;

  static equals(a: ReportLocationRequest | PlainMessage<ReportLocationRequest> | undefined, b: ReportLocationRequest | PlainMessage<ReportLocationRequest> | undefined): boolean;
}

/**
 * @generated from message cargo.tracking.v1.ReportLocationResponse
 */
export declare class ReportLocationResponse extends Message<ReportLocationResponse> {
  /**
   * Echoes the persisted event id (server-assigned if the request left
   * it blank).
   *
   * @generated from field: string id = 1;
   */
  id: string;

  constructor(data?: PartialMessage<ReportLocationResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.tracking.v1.ReportLocationResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReportLocationResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReportLocationResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReportLocationResponse;

  static equals(a: ReportLocationResponse | PlainMessage<ReportLocationResponse> | undefined, b: ReportLocationResponse | PlainMessage<ReportLocationResponse> | undefined): boolean;
}

/**
 * GetTracking — latest snapshot for one shipment, joining the tracking
 * read model with the shipment-status projection maintained from
 * cargo.shipment.events.
 *
 * @generated from message cargo.tracking.v1.GetTrackingRequest
 */
export declare class GetTrackingRequest extends Message<GetTrackingRequest> {
  /**
   * @generated from field: string shipment_id = 1;
   */
  shipmentId: string;

  constructor(data?: PartialMessage<GetTrackingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.tracking.v1.GetTrackingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTrackingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTrackingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTrackingRequest;

  static equals(a: GetTrackingRequest | PlainMessage<GetTrackingRequest> | undefined, b: GetTrackingRequest | PlainMessage<GetTrackingRequest> | undefined): boolean;
}

/**
 * @generated from message cargo.tracking.v1.GetTrackingResponse
 */
export declare class GetTrackingResponse extends Message<GetTrackingResponse> {
  /**
   * @generated from field: string shipment_id = 1;
   */
  shipmentId: string;

  /**
   * @generated from field: cargo.shipment.v1.ShipmentStatus status = 2;
   */
  status: ShipmentStatus;

  /**
   * @generated from field: double last_lat = 3;
   */
  lastLat: number;

  /**
   * @generated from field: double last_lng = 4;
   */
  lastLng: number;

  /**
   * @generated from field: google.protobuf.Timestamp last_update_at = 5;
   */
  lastUpdateAt?: Timestamp;

  constructor(data?: PartialMessage<GetTrackingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.tracking.v1.GetTrackingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTrackingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTrackingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTrackingResponse;

  static equals(a: GetTrackingResponse | PlainMessage<GetTrackingResponse> | undefined, b: GetTrackingResponse | PlainMessage<GetTrackingResponse> | undefined): boolean;
}

/**
 * StreamTracking — server-streaming subscription. The server pushes
 * every new TrackingEvent for `shipment_id` and closes the stream when
 * the shipment reaches DELIVERED or CANCELLED (or the client cancels).
 *
 * @generated from message cargo.tracking.v1.StreamTrackingRequest
 */
export declare class StreamTrackingRequest extends Message<StreamTrackingRequest> {
  /**
   * @generated from field: string shipment_id = 1;
   */
  shipmentId: string;

  constructor(data?: PartialMessage<StreamTrackingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.tracking.v1.StreamTrackingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamTrackingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamTrackingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamTrackingRequest;

  static equals(a: StreamTrackingRequest | PlainMessage<StreamTrackingRequest> | undefined, b: StreamTrackingRequest | PlainMessage<StreamTrackingRequest> | undefined): boolean;
}

/**
 * Streaming frame. Wraps TrackingEvent so the response type follows the
 * `*Response` naming convention required by buf's lint preset.
 *
 * @generated from message cargo.tracking.v1.StreamTrackingResponse
 */
export declare class StreamTrackingResponse extends Message<StreamTrackingResponse> {
  /**
   * @generated from field: cargo.tracking.v1.TrackingEvent event = 1;
   */
  event?: TrackingEvent;

  constructor(data?: PartialMessage<StreamTrackingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cargo.tracking.v1.StreamTrackingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamTrackingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamTrackingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamTrackingResponse;

  static equals(a: StreamTrackingResponse | PlainMessage<StreamTrackingResponse> | undefined, b: StreamTrackingResponse | PlainMessage<StreamTrackingResponse> | undefined): boolean;
}

