// Tracking Service — live geo-location ingest, read model, and
// server-streaming subscriptions for a single shipment.

// @generated by protoc-gen-connect-es v1.6.1
// @generated from file cargo/tracking/v1/tracking.proto (package cargo.tracking.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetTrackingRequest, GetTrackingResponse, ReportLocationRequest, ReportLocationResponse, StreamTrackingRequest, StreamTrackingResponse } from "./tracking_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service cargo.tracking.v1.TrackingService
 */
export declare const TrackingService: {
  readonly typeName: "cargo.tracking.v1.TrackingService",
  readonly methods: {
    /**
     * @generated from rpc cargo.tracking.v1.TrackingService.ReportLocation
     */
    readonly reportLocation: {
      readonly name: "ReportLocation",
      readonly I: typeof ReportLocationRequest,
      readonly O: typeof ReportLocationResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cargo.tracking.v1.TrackingService.GetTracking
     */
    readonly getTracking: {
      readonly name: "GetTracking",
      readonly I: typeof GetTrackingRequest,
      readonly O: typeof GetTrackingResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cargo.tracking.v1.TrackingService.StreamTracking
     */
    readonly streamTracking: {
      readonly name: "StreamTracking",
      readonly I: typeof StreamTrackingRequest,
      readonly O: typeof StreamTrackingResponse,
      readonly kind: MethodKind.ServerStreaming,
    },
  }
};

