// Tracking Service — live geo-location ingest, read model, and
// server-streaming subscriptions for a single shipment.

// @generated by protoc-gen-connect-es v1.6.1
// @generated from file cargo/tracking/v1/tracking.proto (package cargo.tracking.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetTrackingRequest, GetTrackingResponse, ReportLocationRequest, ReportLocationResponse, StreamTrackingRequest, StreamTrackingResponse } from "./tracking_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service cargo.tracking.v1.TrackingService
 */
export const TrackingService = {
  typeName: "cargo.tracking.v1.TrackingService",
  methods: {
    /**
     * @generated from rpc cargo.tracking.v1.TrackingService.ReportLocation
     */
    reportLocation: {
      name: "ReportLocation",
      I: ReportLocationRequest,
      O: ReportLocationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cargo.tracking.v1.TrackingService.GetTracking
     */
    getTracking: {
      name: "GetTracking",
      I: GetTrackingRequest,
      O: GetTrackingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cargo.tracking.v1.TrackingService.StreamTracking
     */
    streamTracking: {
      name: "StreamTracking",
      I: StreamTrackingRequest,
      O: StreamTrackingResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
};

