// Tracking Service — live geo-location ingest, read model, and
// server-streaming subscriptions for a single shipment.

// @generated by protoc-gen-es v1.10.0
// @generated from file cargo/tracking/v1/tracking.proto (package cargo.tracking.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";
import { ShipmentStatus } from "../../shipment/v1/shipment_pb.js";

/**
 * A single geo-location ping reported for a shipment.
 *
 * @generated from message cargo.tracking.v1.TrackingEvent
 */
export const TrackingEvent = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.tracking.v1.TrackingEvent",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "shipment_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "lat", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "lng", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "recorded_at", kind: "message", T: Timestamp },
    { no: 6, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * ReportLocation — push a single tracking ping. Idempotent on event.id
 * so retries (e.g. from the simulated test client) are safe.
 *
 * @generated from message cargo.tracking.v1.ReportLocationRequest
 */
export const ReportLocationRequest = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.tracking.v1.ReportLocationRequest",
  () => [
    { no: 1, name: "event", kind: "message", T: TrackingEvent },
  ],
);

/**
 * @generated from message cargo.tracking.v1.ReportLocationResponse
 */
export const ReportLocationResponse = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.tracking.v1.ReportLocationResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * GetTracking — latest snapshot for one shipment, joining the tracking
 * read model with the shipment-status projection maintained from
 * cargo.shipment.events.
 *
 * @generated from message cargo.tracking.v1.GetTrackingRequest
 */
export const GetTrackingRequest = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.tracking.v1.GetTrackingRequest",
  () => [
    { no: 1, name: "shipment_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message cargo.tracking.v1.GetTrackingResponse
 */
export const GetTrackingResponse = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.tracking.v1.GetTrackingResponse",
  () => [
    { no: 1, name: "shipment_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "status", kind: "enum", T: proto3.getEnumType(ShipmentStatus) },
    { no: 3, name: "last_lat", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "last_lng", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "last_update_at", kind: "message", T: Timestamp },
  ],
);

/**
 * StreamTracking — server-streaming subscription. The server pushes
 * every new TrackingEvent for `shipment_id` and closes the stream when
 * the shipment reaches DELIVERED or CANCELLED (or the client cancels).
 *
 * @generated from message cargo.tracking.v1.StreamTrackingRequest
 */
export const StreamTrackingRequest = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.tracking.v1.StreamTrackingRequest",
  () => [
    { no: 1, name: "shipment_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * Streaming frame. Wraps TrackingEvent so the response type follows the
 * `*Response` naming convention required by buf's lint preset.
 *
 * @generated from message cargo.tracking.v1.StreamTrackingResponse
 */
export const StreamTrackingResponse = /*@__PURE__*/ proto3.makeMessageType(
  "cargo.tracking.v1.StreamTrackingResponse",
  () => [
    { no: 1, name: "event", kind: "message", T: TrackingEvent },
  ],
);

